/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kcnicole' at '1/3/17 7:00 PM' with Gradle 2.14.1
 *
 * @author kcnicole, @date 1/3/17 7:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
